language: rust

before_script:
  - rustup component add rustfmt-preview

matrix:
  include:
    - os: osx
      rust: nightly
      script:
        - cargo build
        - cargo test --verbose

    - os: linux
      rust: nightly
      script:
        - cargo build
        - cargo test --verbose
