language: rust

# pin temporarily because rustfmt is not available in nightly
rust:
  - nightly-2020-07-11

before_script:
  - rustup component add rustfmt-preview
  - cargo fmt --all -- --check

matrix:
  include:
    - os: osx
      script:
        - cargo build
        - cargo test --verbose

    - os: linux
      script:
        - cargo build
        - cargo test --verbose
